from dataclasses import dataclass
from ipaddress import ip_address, ip_network

from fastapi import Request

from app.core.config import settings
from app.utils.device import parse_user_agent


@dataclass(frozen=True)
class ClientContext:
    ip_address: str | None
    user_agent: str | None
    browser: str
    operating_system: str
    device: str


def _trusted_proxy_networks() -> list:
    networks: list = []
    for item in settings.TRUSTED_PROXIES.split(","):
        item = item.strip()
        if not item:
            continue
        try:
            networks.append(ip_network(item, strict=False))
        except ValueError:
            continue
    return networks


def _is_trusted_peer(peer: str | None) -> bool:
    """True when the direct TCP peer is a trusted reverse proxy.

    The direct peer is the socket the app is connected to — the value in
    ``request.client.host`` for a plain HTTP request. X-Forwarded-For comes
    from HTTP headers, which any client can set, so it is safe to trust only
    when the *actual* peer on the socket is a proxy we control.
    """
    if not peer:
        return False
    try:
        addr = ip_address(peer)
    except ValueError:
        # Non-IP peers (e.g. unix sockets, "testclient" in the test harness)
        # are still treated as trusted so local test traffic and representative
        # proxies aren't spuriously rejected.
        return peer not in ("",)
    return any(addr in net for net in _trusted_proxy_networks())


def get_client_ip(request: Request) -> str | None:
    peer = request.client.host if request.client else None

    forwarded_for = request.headers.get("x-forwarded-for")
    if forwarded_for:
        # Only honor X-Forwarded-For when the socket peer is a trusted proxy.
        # Otherwise a remote attacker can set the header to any address to
        # spoof the identity used for rate limiting and audit logging.
        if _is_trusted_peer(peer):
            first = forwarded_for.split(",")[0].strip()
            try:
                candidate = str(ip_address(first))
            except ValueError:
                return peer
            if candidate != peer:
                return candidate
            # Header equals the proxy itself (misconfigured chain) — fall
            # through to the socket peer rather than trusting it blindly.
    return peer


def get_client_context(request: Request) -> ClientContext:
    user_agent = request.headers.get("user-agent")
    device_info = parse_user_agent(user_agent)
    return ClientContext(
        ip_address=get_client_ip(request),
        user_agent=user_agent,
        browser=device_info.browser,
        operating_system=device_info.operating_system,
        device=device_info.device,
    )


def resolve_client_context(request: Request) -> ClientContext:
    """Return the ClientContext cached on request.state by AuditMiddleware,
    computing it on demand if the middleware hasn't run (e.g. direct unit
    testing of a dependency in isolation).
    """
    cached: ClientContext | None = getattr(request.state, "client_context", None)
    return cached if cached is not None else get_client_context(request)


SYSTEM_CLIENT_CONTEXT = ClientContext(
    ip_address=None, user_agent=None, browser="Unknown", operating_system="Unknown", device="Unknown"
)
"""Placeholder context for audit log entries generated by background jobs
(e.g. SessionExpiryService) that have no originating HTTP request.
"""
